# Generated by Django 3.1.12 on 2026-04-15 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Prete', 'Prete'), ('Reserve', 'Reserve'), ('Maintenance', 'Maintenance'), ('Hors Service', 'Hors Service')], default='Prete', max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('sessions', models.IntegerField(default=0)),
                ('hours', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='RaspiDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raspi_id', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raspi', to='machines.machine')),
            ],
            options={
                'db_table': 'raspi_devices',
            },
        ),
    ]
