# Generated by Django 5.2.17 on 2026-08-15 22:20

from django.db import migrations, models


def dedupe_roles(apps, schema_editor):
    """Keep the lowest-id Role per name; repoint users then delete the rest.

    User.role has on_delete=CASCADE, so duplicate roles must be removed
    (not just merged) to avoid deleting users.
    """
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")
    for name in Role.objects.values_list("name", flat=True).distinct():
        rows = list(Role.objects.filter(name=name).order_by("id"))
        if len(rows) <= 1:
            continue
        keep, dups = rows[0], rows[1:]
        User.objects.filter(role__in=dups).update(role=keep)
        Role.objects.filter(id__in=[d.id for d in dups]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passwordresetrequest_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]