# Generated by Django 4.2.27 on 2026-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_inscription_user_etat_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
