# Generated by Django 4.2.27 on 2026-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_profile_picture_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='etat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
