# Generated by Django 4.2.27 on 2026-01-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_login',
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
