# Generated by Django 3.1.12 on 2026-07-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_is_active'),
        ('accounts', '0005_alter_role_id'),
    ]

    operations = [
    ]
