# Generated by Django 3.1.12 on 2026-01-31 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='planifiée', max_length=20)),
                ('complications', models.TextField(blank=True, max_length=255, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='machines.machine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='patients.patient')),
            ],
            options={
                'db_table': 'seances',
            },
        ),
        migrations.CreateModel(
            name='PreSessionMeasurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('weight', models.FloatField(default=0.0)),
                ('heart_rate', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('saturation', models.FloatField(default=0.0)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_measurements', to='seances.seance')),
            ],
            options={
                'db_table': 'pre_session_measurements',
            },
        ),
        migrations.CreateModel(
            name='PostSessionMeasurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('weight', models.FloatField(default=0.0)),
                ('heart_rate', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('saturation', models.FloatField(default=0.0)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_measurements', to='seances.seance')),
            ],
            options={
                'db_table': 'post_session_measurements',
            },
        ),
    ]
