# Generated by Django 3.1.12 on 2026-07-18 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='planifiée', max_length=20)),
                ('complications', models.TextField(blank=True, max_length=255, null=True)),
                ('blood_flow_min', models.FloatField(default=150)),
                ('blood_flow_max', models.FloatField(default=400)),
                ('blood_flow_critical_low', models.FloatField(default=100)),
                ('blood_flow_critical_high', models.FloatField(default=450)),
                ('arterial_pressure_min', models.FloatField(default=90)),
                ('arterial_pressure_max', models.FloatField(default=180)),
                ('arterial_pressure_critical_low', models.FloatField(default=70)),
                ('arterial_pressure_critical_high', models.FloatField(default=200)),
                ('venous_pressure_min', models.FloatField(default=50)),
                ('venous_pressure_max', models.FloatField(default=250)),
                ('venous_pressure_critical_low', models.FloatField(default=30)),
                ('venous_pressure_critical_high', models.FloatField(default=280)),
                ('tmp_min', models.FloatField(default=-50)),
                ('tmp_max', models.FloatField(default=300)),
                ('tmp_critical_low', models.FloatField(default=-80)),
                ('tmp_critical_high', models.FloatField(default=350)),
                ('uf_rate_min', models.FloatField(default=0)),
                ('uf_rate_max', models.FloatField(default=1000)),
                ('uf_rate_critical_high', models.FloatField(default=1200)),
                ('uf_volume_min', models.FloatField(default=0)),
                ('uf_volume_max', models.FloatField(default=4000)),
                ('uf_volume_critical_high', models.FloatField(default=5000)),
                ('heparin_min', models.FloatField(default=0)),
                ('heparin_max', models.FloatField(default=2000)),
                ('heparin_critical_high', models.FloatField(default=2500)),
                ('debit', models.IntegerField(choices=[(20, 'Critique – 1 image / 20s'), (30, 'Modéré  – 1 image / 30s'), (60, 'Normal  – 1 image / 60s')], default=60, help_text="Intervalle d'envoi d'image en secondes. 20 = critique, 30 = modéré, 60 = normal.")),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='machines.machine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='patients.patient')),
            ],
            options={
                'db_table': 'seances',
            },
        ),
        migrations.CreateModel(
            name='RapportSeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('contenu_html', models.TextField()),
                ('qualite_seance', models.CharField(choices=[('normale', 'Normale'), ('difficile', 'Difficile')], default='normale', max_length=20)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='seances.seance')),
            ],
            options={
                'verbose_name': 'Rapport de séance',
                'verbose_name_plural': 'Rapports de séances',
            },
        ),
        migrations.CreateModel(
            name='PreSessionMeasurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('weight', models.FloatField(default=0.0)),
                ('heart_rate', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('saturation', models.FloatField(default=0.0)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_measurements', to='seances.seance')),
            ],
            options={
                'db_table': 'pre_session_measurements',
            },
        ),
        migrations.CreateModel(
            name='PostSessionMeasurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('weight', models.FloatField(default=0.0)),
                ('heart_rate', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('saturation', models.FloatField(default=0.0)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_measurements', to='seances.seance')),
            ],
            options={
                'db_table': 'post_session_measurements',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('danger_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Modéré'), ('HIGH', 'Critique')], max_length=10)),
                ('recommended_action', models.TextField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='seances.seance')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
