# Generated by Django 3.1.12 on 2026-07-17 22:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='arterial_pressure_critical_high',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='seance',
            name='arterial_pressure_critical_low',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='seance',
            name='arterial_pressure_max',
            field=models.FloatField(default=180),
        ),
        migrations.AddField(
            model_name='seance',
            name='arterial_pressure_min',
            field=models.FloatField(default=90),
        ),
        migrations.AddField(
            model_name='seance',
            name='blood_flow_critical_high',
            field=models.FloatField(default=450),
        ),
        migrations.AddField(
            model_name='seance',
            name='blood_flow_critical_low',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='seance',
            name='blood_flow_max',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='seance',
            name='blood_flow_min',
            field=models.FloatField(default=150),
        ),
        migrations.AddField(
            model_name='seance',
            name='debit',
            field=models.IntegerField(choices=[(20, 'Critique – 1 image / 20s'), (30, 'Modéré  – 1 image / 30s'), (60, 'Normal  – 1 image / 60s')], default=60, help_text="Intervalle d'envoi d'image en secondes. 20 = critique, 30 = modéré, 60 = normal."),
        ),
        migrations.AddField(
            model_name='seance',
            name='heparin_critical_high',
            field=models.FloatField(default=2500),
        ),
        migrations.AddField(
            model_name='seance',
            name='heparin_max',
            field=models.FloatField(default=2000),
        ),
        migrations.AddField(
            model_name='seance',
            name='heparin_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seance',
            name='tmp_critical_high',
            field=models.FloatField(default=350),
        ),
        migrations.AddField(
            model_name='seance',
            name='tmp_critical_low',
            field=models.FloatField(default=-80),
        ),
        migrations.AddField(
            model_name='seance',
            name='tmp_max',
            field=models.FloatField(default=300),
        ),
        migrations.AddField(
            model_name='seance',
            name='tmp_min',
            field=models.FloatField(default=-50),
        ),
        migrations.AddField(
            model_name='seance',
            name='uf_rate_critical_high',
            field=models.FloatField(default=1200),
        ),
        migrations.AddField(
            model_name='seance',
            name='uf_rate_max',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='seance',
            name='uf_rate_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seance',
            name='uf_volume_critical_high',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='seance',
            name='uf_volume_max',
            field=models.FloatField(default=4000),
        ),
        migrations.AddField(
            model_name='seance',
            name='uf_volume_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seance',
            name='venous_pressure_critical_high',
            field=models.FloatField(default=280),
        ),
        migrations.AddField(
            model_name='seance',
            name='venous_pressure_critical_low',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='seance',
            name='venous_pressure_max',
            field=models.FloatField(default=250),
        ),
        migrations.AddField(
            model_name='seance',
            name='venous_pressure_min',
            field=models.FloatField(default=50),
        ),
        migrations.CreateModel(
            name='RapportSeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('contenu_html', models.TextField()),
                ('qualite_seance', models.CharField(choices=[('normale', 'Normale'), ('difficile', 'Difficile')], default='normale', max_length=20)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='seances.seance')),
            ],
            options={
                'verbose_name': 'Rapport de séance',
                'verbose_name_plural': 'Rapports de séances',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('danger_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Modéré'), ('HIGH', 'Critique')], max_length=10)),
                ('recommended_action', models.TextField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='seances.seance')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
