# Generated by Django 5.2.17 on 2026-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_alter_alert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouvelle'), ('ACK', 'Acquittée'), ('RESOLVED', 'Résolue')], default='NEW', max_length=10),
        ),
    ]
