# Generated by Django 3.1.12 on 2026-02-20 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='machines.machinetypemodule')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_measurements', to='seances.seance')),
            ],
            options={
                'db_table': 'live_measurements',
            },
        ),
        migrations.AddIndex(
            model_name='livemeasurement',
            index=models.Index(fields=['seance', 'module', '-timestamp'], name='live_measur_seance__6684c1_idx'),
        ),
    ]
