# Generated by Django 3.1.12 on 2026-02-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='livemeasurement',
            name='live_measur_seance__6684c1_idx',
        ),
        migrations.RemoveField(
            model_name='livemeasurement',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='livemeasurement',
            name='module',
        ),
        migrations.RemoveField(
            model_name='livemeasurement',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='livemeasurement',
            name='value',
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='Debit_sang',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='Heparine',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='PA',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='PTM',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='PV',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='Taux_UF',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='Volume_UF',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='seances.seance'),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='livemeasurement',
            table='vital_readings',
        ),
    ]
