# Generated by Django 3.1.12 on 2026-07-17 22:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_auto_20260717_2326'),
        ('monitoring', '0002_auto_20260226_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_logs',
            },
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='Debit_sang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='Heparine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='PA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='PTM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='PV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='Taux_UF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='Volume_UF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livemeasurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='livemeasurement',
            table='live_measurements',
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Debit_sang', models.FloatField(blank=True, null=True)),
                ('Taux_UF', models.FloatField(blank=True, null=True)),
                ('PA', models.FloatField(blank=True, null=True)),
                ('PTM', models.FloatField(blank=True, null=True)),
                ('PV', models.FloatField(blank=True, null=True)),
                ('Volume_UF', models.FloatField(blank=True, null=True)),
                ('Heparine', models.FloatField(blank=True, null=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='seances.seance')),
            ],
            options={
                'db_table': 'vital_readings',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='monitoring.vitalreading')),
            ],
            options={
                'db_table': 'alertes',
            },
        ),
    ]
