# Generated by Django 3.1.12 on 2026-07-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20260724_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouvelle'), ('ACK', 'Acquittée'), ('DONE', 'Résolue')], default='NEW', max_length=10),
        ),
    ]
