# Generated by Django 3.1.12 on 2026-07-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alerte_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='status',
            field=models.CharField(default='NEW', max_length=10),
        ),
        migrations.AlterModelTable(
            name='alerte',
            table=None,
        ),
    ]
