# Generated by Django 5.2.4 on 2026-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20260726_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeasurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/'),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='source',
            field=models.CharField(blank=True, default='AI_OCR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livemeasurement',
            name='status_validation',
            field=models.CharField(blank=True, default='VALIDATED', max_length=20, null=True),
        ),
    ]
