# Generated by Django 3.1.12 on 2026-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(default=None)),
                ('group_sangune', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3)),
                ('type_dialyse', models.CharField(choices=[('Hémodialyse', 'Hémodialyse'), ('Dialyse péritonéale', 'Dialyse péritonéale'), ('Transplantation rénale', 'Transplantation rénale')], default='Hémodialyse', max_length=25)),
                ('adresse', models.CharField(default='Tunisie', max_length=255)),
                ('telephone', models.CharField(default='', max_length=15)),
                ('contact_urgence', models.CharField(default='', max_length=15)),
                ('antecedents_med', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
