# Generated by Django 3.1.12 on 2026-07-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default=None)),
                ('age', models.IntegerField()),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3)),
                ('type_de_dialyse', models.CharField(choices=[('Hémodialyse', 'Hémodialyse'), ('Dialyse péritonéale', 'Dialyse péritonéale'), ('Transplantation rénale', 'Transplantation rénale')], default='', max_length=50)),
                ('adresse', models.CharField(default='Tunisie', max_length=255)),
                ('telephone', models.CharField(default='', max_length=15)),
                ('contact_urgence', models.CharField(default='', max_length=15)),
                ('antecedents_medicaux', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
