# Generated by Django 3.1.12 on 2026-01-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
    migrations.AddField(
        model_name='patient',
        name='adresse',
        field=models.CharField(default='Tunisie', max_length=255),
    ),
    migrations.AddField(
        model_name='patient',
        name='antecedents_medicaux',
        field=models.CharField(default='', max_length=255),
    ),
    migrations.AddField(
        model_name='patient',
        name='contact_urgence',
        field=models.CharField(default='', max_length=15),
    ),
    migrations.AddField(
        model_name='patient',
        name='date_of_birth',
        field=models.DateField(default=None),
    ),
    migrations.AddField(
        model_name='patient',
        name='groupe_sanguin',
        field=models.CharField(default='', max_length=3),
    ),
    migrations.AddField(
        model_name='patient',
        name='telephone',
        field=models.CharField(default='', max_length=15),
    ),
    migrations.AddField(
        model_name='patient',
        name='type_de_dialyse',
        field=models.CharField(default='', max_length=50),
    ),
]
