# Generated by Django 3.1.12 on 2026-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20260128_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type_de_dialyse',
            field=models.CharField(choices=[('Hémodialyse', 'Hémodialyse'), ('Dialyse péritonéale', 'Dialyse péritonéale'), ('Transplantation rénale', 'Transplantation rénale')], default='', max_length=50),
        ),
    ]
