# Generated by Django 3.1.12 on 2026-07-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20260128_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='antecedents_med',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='group_sangune',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='type_dialyse',
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
